variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

image: docker-spv.artifactory.gscorp.ad/lippia_spv_adapter:3.2.1.1

stages:
  - build
  - testReporte
  - testManual
  - PublishReport

cache:
  paths:
    - .m2

Build:
  stage: build
  script:
    - mvn compile

Test-Reporte:
  stage: testReporte
  script:
    - mvn -P $PROFILE -DforkCount=0 clean test "-Dcucumber.tags=--tags $TAG"
  artifacts:
    name: $CI_BUILD_NAME_$CI_PIPELINE_ID
    when: always
    paths:
      - target/spark-reports/
  only:
    - schedules

Test-ADemanda:
  stage: testManual
  script:
    - mvn -P $PROFILE -DforkCount=0 clean test "-Dcucumber.tags=--tags $TAG"
  artifacts:
    name: $CI_BUILD_NAME_$CI_PIPELINE_ID
    when: always
    paths:
      - target/spark-reports/
  only:
    - web

pages:
  stage: PublishReport
  script:
    - echo "Publish Test Reports"
    - mv target/spark-reports public
    - echo "URL:https://desarrollo.gitlab.gscorp.ad/tarjetas/test-bff-obi-tarjetas/"
  artifacts:
    paths:
      - public
  only:
    - schedules
    - web
  when: always